version: '3.7'

services:
  api-skeleton:
    container_name: api-skeleton
    build:
      context: .
    environment:
      - TZ=Asia/Seoul
      - env=${ENV:-local}
      - "heapOpt=-Xms256m -Xmx256m"
    ports:
      - "8080:8080"
    sysctls:
      - net.core.somaxconn=65000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
